version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: galactic_cats
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: galactic_cats
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: