spring:
    application:
        name: space-cats-market

    profiles:
        active: local

    security:
        oauth2:
            resourceserver:
                jwt:
                    jws-algorithms: RS256
                    jwk-set-uri: http://localhost:8083/.well-known/jwks.json
            client:
                registration:
                    github:
                        clientId: ${GITHUB_CLIENT_ID}
                        clientSecret: ${GITHUB_CLIENT_SECRET}
                        scope: user:email
                        redirect-uri: http://localhost:8080/login/oauth2/code/github
                        authorization-grant-type: authorization_code
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user

    datasource:
        url: jdbc:postgresql://localhost:5432/galactic_cats
        username: postgres
        password: root

    liquibase:
        change-log: classpath:liquibase/changelog.yaml
        enabled: true

application:
    feature:
        toggles:
            cosmoCats:
                enabled: false
            kittyProducts:
                enabled: false