spring:
    application:
        name: space-cats-market
        
    liquibase:
        change-log: classpath:liquibase/changelog.yaml
        enabled: true

application:
    feature:
        toggles:
            cosmoCats:
                enabled: false
            kittyProducts:
                enabled: false